export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
//export const LOGIN_FAIL = "LOGIN_FAIL";
//export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
//export const REGISTER_FAIL = "REGISTER_FAIL";
